### ISSUE TITLE
load_vectors() missing 1 required positional argument: 'vectors'

### ISSUE THREAD

**Issue by doulemint** [uwnlp/verb-attributes#2]
Hi, Thank you for contributing this awesome project!
There are some code patches and resources that is out-of-date, could u update them?
like the dictionary pickle file, and there is no torch.0.3.0 post 4 version available.
So the text.vocab.load_vector() require different arguments...

Thank you in advance

**Comment by doulemint** [comment]
Does anyone have ever run it? it seems require a lot memory when running data/arttitude_loader.py of load_word_vectors function?emmm, it crashed when I run it

**Comment by rowanz** [comment]
Thanks! Sorry, this codebase is intended to be archival (exactly what I did to run the experiments in my paper) so I don't have plans to update it at this time. Does installing [torch](https://pypi.org/project/torch/0.3.0.post4/) in a virtualenv or conda env work?

**Comment by doulemint** [comment]
Thank you for your promptly reply!! The last question: Have you ever run into a problem that it takes too long to load glove pretrained vectors?  


```
> def load_word_vectors(root, wv_type, dim):
>     """Load word vectors from a path, trying .pt, .txt, and .zip extensions."""
>     if isinstance(dim, int):
>         dim = str(dim) + 'd'
>     fname = os.path.join(root, wv_type + '.' + dim)
>     if os.path.isfile(fname + '.pt'):
>         fname_pt = fname + '.pt'
>         print('loading word vectors from', fname_pt)
>         return torch.load(fname_pt)
>     if os.path.isfile(fname + '.txt'):
>         fname_txt = fname + '.txt'
>         cm = open(fname_txt, 'rb')
>         cm = [line for line in cm]
>     elif os.path.basename(wv_type) in URL:
>         url = URL[wv_type]
>         print('downloading word vectors from {}'.format(url))
>         filename = os.path.basename(fname)
>         if not os.path.exists(root):
>             os.makedirs(root)
>         with tqdm(unit='B', unit_scale=True, miniters=1, desc=filename) as t:
>             fname, _ = urlretrieve(url, fname, reporthook=reporthook(t))
>             with zipfile.ZipFile(fname, "r") as zf:
>                 print('extracting word vectors into {}'.format(root))
>                 zf.extractall(root)
>         if not os.path.isfile(fname + '.txt'):
>             raise RuntimeError('no word vectors of requested dimension found')
>         return load_word_vectors(root, wv_type, dim)
>     else:
>         raise RuntimeError('unable to load word vectors')
> wv_dict, wv_arr, _ = load_word_vectors(GLOVE_PATH, GLOVE_TYPE, 300)
> 
```

the snippet from [here](https://github.com/uwnlp/verb-attributes/blob/master/data/attribute_loader.py)

**load_word_vectors** function is supposed to return two useful variables. But If **‘txt’** extension is passed to it, nothing would be returned. 

```
> if os.path.isfile(fname + '.txt'):
>         fname_txt = fname + '.txt'
>         cm = open(fname_txt, 'rb')
>         cm = [line for line in cm]
```

you may miss out this, or you had been used 'pt' extension file.

I assume that your experiment was trained on 840B 300-dimensional GloVe vectors. so **glove.840B.300d.txt** should be downloaded. However, it's usually too large to load to memory easily. 

Thank you for reading this long reply :D

> Thanks! Sorry, this codebase is intended to be archival (exactly what I did to run the experiments in my paper) so I don't have plans to update it at this time. Does installing [torch](https://pypi.org/project/torch/0.3.0.post4/) in a virtualenv or conda env work?

**Comment by rowanz** [comment]
I haven't (I guess I have enough memory on my machine or I must have used the preconverted `pt` vectors), sorry!

**Comment by doulemint** [comment]
Got it! My questions solved. I'll close this pr
